-- Topezia — starter taxonomy seed, translated from prisma/seed.ts (same
-- reason as hand_written_init.sql: Prisma CLI unreachable from this sandbox).

INSERT INTO "Vertical" (slug, name, "isDeepTier", "cardLayout") VALUES
  ('tech-software', 'Tech & Software', true, 'KNOWLEDGE_WORK'),
  ('marketing-creative', 'Marketing & Creative', true, 'KNOWLEDGE_WORK'),
  ('healthcare-allied', 'Healthcare — Allied Health', true, 'STRUCTURED_HOURLY'),
  ('trucking-logistics', 'Trucking & Logistics', true, 'STRUCTURED_HOURLY'),
  ('sales', 'Sales', false, 'KNOWLEDGE_WORK'),
  ('finance-accounting', 'Finance & Accounting', false, 'KNOWLEDGE_WORK'),
  ('customer-support', 'Customer Support', false, 'KNOWLEDGE_WORK'),
  ('retail-hospitality', 'Retail & Hospitality', false, 'STRUCTURED_HOURLY');

INSERT INTO "Role" (slug, name, "verticalId") VALUES
  ('backend-engineer', 'Backend Engineer', (SELECT id FROM "Vertical" WHERE slug='tech-software')),
  ('frontend-engineer', 'Frontend Engineer', (SELECT id FROM "Vertical" WHERE slug='tech-software')),
  ('fullstack-engineer', 'Full-Stack Engineer', (SELECT id FROM "Vertical" WHERE slug='tech-software')),
  ('devops-engineer', 'DevOps Engineer', (SELECT id FROM "Vertical" WHERE slug='tech-software')),
  ('data-engineer', 'Data Engineer', (SELECT id FROM "Vertical" WHERE slug='tech-software')),
  ('graphic-designer', 'Graphic Designer', (SELECT id FROM "Vertical" WHERE slug='marketing-creative')),
  ('video-editor', 'Video Editor', (SELECT id FROM "Vertical" WHERE slug='marketing-creative')),
  ('content-marketer', 'Content Marketer', (SELECT id FROM "Vertical" WHERE slug='marketing-creative')),
  ('social-media-manager', 'Social Media Manager', (SELECT id FROM "Vertical" WHERE slug='marketing-creative')),
  ('physical-therapist', 'Physical Therapist', (SELECT id FROM "Vertical" WHERE slug='healthcare-allied')),
  ('radiologic-technologist', 'Radiologic Technologist', (SELECT id FROM "Vertical" WHERE slug='healthcare-allied')),
  ('respiratory-therapist', 'Respiratory Therapist', (SELECT id FROM "Vertical" WHERE slug='healthcare-allied')),
  ('occupational-therapist', 'Occupational Therapist', (SELECT id FROM "Vertical" WHERE slug='healthcare-allied')),
  ('lab-technician', 'Lab Technician', (SELECT id FROM "Vertical" WHERE slug='healthcare-allied')),
  ('otr-driver', 'OTR Truck Driver', (SELECT id FROM "Vertical" WHERE slug='trucking-logistics')),
  ('local-cdl-driver', 'Local CDL Driver', (SELECT id FROM "Vertical" WHERE slug='trucking-logistics')),
  ('dispatcher', 'Dispatcher', (SELECT id FROM "Vertical" WHERE slug='trucking-logistics'));

INSERT INTO "RoleAlias" ("rawText", "roleId", "resolvedBy") VALUES
  ('Backend Developer', (SELECT id FROM "Role" WHERE slug='backend-engineer'), 'MANUAL'),
  ('Server-side Engineer', (SELECT id FROM "Role" WHERE slug='backend-engineer'), 'MANUAL'),
  ('API Engineer', (SELECT id FROM "Role" WHERE slug='backend-engineer'), 'MANUAL'),
  ('Frontend Developer', (SELECT id FROM "Role" WHERE slug='frontend-engineer'), 'MANUAL'),
  ('React Developer', (SELECT id FROM "Role" WHERE slug='frontend-engineer'), 'MANUAL'),
  ('UI Developer', (SELECT id FROM "Role" WHERE slug='frontend-engineer'), 'MANUAL'),
  ('Full Stack Developer', (SELECT id FROM "Role" WHERE slug='fullstack-engineer'), 'MANUAL'),
  ('Fullstack Developer', (SELECT id FROM "Role" WHERE slug='fullstack-engineer'), 'MANUAL'),
  ('Site Reliability Engineer', (SELECT id FROM "Role" WHERE slug='devops-engineer'), 'MANUAL'),
  ('Platform Engineer', (SELECT id FROM "Role" WHERE slug='devops-engineer'), 'MANUAL'),
  ('SRE', (SELECT id FROM "Role" WHERE slug='devops-engineer'), 'MANUAL'),
  ('Data Pipeline Engineer', (SELECT id FROM "Role" WHERE slug='data-engineer'), 'MANUAL'),
  ('Analytics Engineer', (SELECT id FROM "Role" WHERE slug='data-engineer'), 'MANUAL'),
  ('Visual Designer', (SELECT id FROM "Role" WHERE slug='graphic-designer'), 'MANUAL'),
  ('Brand Designer', (SELECT id FROM "Role" WHERE slug='graphic-designer'), 'MANUAL'),
  ('Videographer', (SELECT id FROM "Role" WHERE slug='video-editor'), 'MANUAL'),
  ('Video Producer', (SELECT id FROM "Role" WHERE slug='video-editor'), 'MANUAL'),
  ('Content Strategist', (SELECT id FROM "Role" WHERE slug='content-marketer'), 'MANUAL'),
  ('Copywriter', (SELECT id FROM "Role" WHERE slug='content-marketer'), 'MANUAL'),
  ('Social Media Coordinator', (SELECT id FROM "Role" WHERE slug='social-media-manager'), 'MANUAL'),
  ('Community Manager', (SELECT id FROM "Role" WHERE slug='social-media-manager'), 'MANUAL'),
  ('PT', (SELECT id FROM "Role" WHERE slug='physical-therapist'), 'MANUAL'),
  ('Physiotherapist', (SELECT id FROM "Role" WHERE slug='physical-therapist'), 'MANUAL'),
  ('Rad Tech', (SELECT id FROM "Role" WHERE slug='radiologic-technologist'), 'MANUAL'),
  ('Imaging Tech', (SELECT id FROM "Role" WHERE slug='radiologic-technologist'), 'MANUAL'),
  ('X-Ray Tech', (SELECT id FROM "Role" WHERE slug='radiologic-technologist'), 'MANUAL'),
  ('RT', (SELECT id FROM "Role" WHERE slug='respiratory-therapist'), 'MANUAL'),
  ('RRT', (SELECT id FROM "Role" WHERE slug='respiratory-therapist'), 'MANUAL'),
  ('OT', (SELECT id FROM "Role" WHERE slug='occupational-therapist'), 'MANUAL'),
  ('Medical Lab Tech', (SELECT id FROM "Role" WHERE slug='lab-technician'), 'MANUAL'),
  ('MLT', (SELECT id FROM "Role" WHERE slug='lab-technician'), 'MANUAL'),
  ('Over the Road Driver', (SELECT id FROM "Role" WHERE slug='otr-driver'), 'MANUAL'),
  ('Long Haul Driver', (SELECT id FROM "Role" WHERE slug='otr-driver'), 'MANUAL'),
  ('Local Delivery Driver', (SELECT id FROM "Role" WHERE slug='local-cdl-driver'), 'MANUAL'),
  ('CDL-A Local', (SELECT id FROM "Role" WHERE slug='local-cdl-driver'), 'MANUAL'),
  ('Fleet Dispatcher', (SELECT id FROM "Role" WHERE slug='dispatcher'), 'MANUAL'),
  ('Logistics Coordinator', (SELECT id FROM "Role" WHERE slug='dispatcher'), 'MANUAL');

INSERT INTO "Skill" (slug, name) VALUES
  ('python', 'Python'),
  ('javascript', 'JavaScript'),
  ('typescript', 'TypeScript'),
  ('react', 'React'),
  ('node-js', 'Node.js'),
  ('fastapi', 'FastAPI'),
  ('aws', 'AWS'),
  ('docker', 'Docker'),
  ('kubernetes', 'Kubernetes'),
  ('postgresql', 'PostgreSQL'),
  ('sql', 'SQL'),
  ('system-design', 'System Design'),
  ('adobe-photoshop', 'Adobe Photoshop'),
  ('adobe-illustrator', 'Adobe Illustrator'),
  ('figma', 'Figma'),
  ('video-editing', 'Video Editing'),
  ('seo', 'SEO'),
  ('copywriting', 'Copywriting'),
  ('social-media-strategy', 'Social Media Strategy'),
  ('patient-care', 'Patient Care'),
  ('ekg', 'EKG'),
  ('ventilator-management', 'Ventilator Management'),
  ('physical-assessment', 'Physical Assessment'),
  ('cdl-class-a', 'CDL Class A'),
  ('cdl-class-b', 'CDL Class B'),
  ('hazmat-endorsement', 'Hazmat Endorsement'),
  ('dot-compliance', 'DOT Compliance');
